mode: 'graphics'

model_params:
  name: 'Decoder'
  in_channels: 1
  latent_dim: 256

vae_chkpt: "/spaths/checkpoints/sym_embedding_BetaVAE/version_0/checkpoints/last.ckpt"


vae_params:
  name: 'BetaVAE'
  in_channels: 1
  latent_dim: 256
  loss_type: 'H'
  beta: 1.0

path_params:
  train_path: "/spaths/datasets/pilot"
  test_path: "/spaths/datasets/pilot_test"

loader_params:
  batch_size: 36
  num_workers: 4

exp_params:
  LR: 0.01
  weight_decay: 0.0
  scheduler_gamma: 0.8
  kld_weight: 0.0001
  manual_seed: 1265

trainer_params:
  max_epochs: 10

logging_params:
  save_dir: "/spaths/checkpoints"
  manual_seed: 1265
