arch: 'ImplicitNeuralModule'

arch_params:
  theta_input: 258
  theta_out: 1
  theta_hidden: 256

path_params:
  train_path: "/spaths/datasets/pilot_embedded"
  test_path: "/spaths/datasets/pilot_test_embedded"

loader_params:
  batch_size: 4
  num_workers: 4

exp_params:
  lr: 0.001
  weight_decay: 0.0
  sched_gamma: 0.8

trainer_params:
  max_epochs: 10

logging_params:
  save_dir: "/spaths/checkpoints"
  manual_seed: 1265
