bootstrap: docker
from: nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04

%environment
 export PATH=$PATH:"/usr/local/julia-1.7.1/bin"

%runscript
  exec bash "$@"

%post
 export DEBIAN_FRONTEND=noninteractive
 export TZ=Etc/UTC
 apt-get update
 apt-get install -y software-properties-common
 apt-get install -y  build-essential \
                     git \
                     wget \
                     ffmpeg \
                     cmake \
                     python3-dev \
                     python3-pip

 apt-get clean

 python3 -m pip install --upgrade pip
 python3 -m pip install pipenv virtualenv

 # setup julia
 wget "https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.1-linux-x86_64.tar.gz" \
     -O "julia.tar.gz"
 tar -xzf "julia.tar.gz" -C "/usr/local/"
 rm "julia.tar.gz"


 # Add an sbatch workaround
 echo '#!/bin/bash\nssh -y "$HOSTNAME"  sbatch "$@"'  > /usr/bin/sbatch
 chmod +x /usr/bin/sbatch

 # Add an scancel workaround
 echo '#!/bin/bash\nssh -y "$HOSTNAME"  scancel "$@"'  > /usr/bin/scancel
 chmod +x /usr/bin/scancel

 # Add an srun workaround
 echo '#!/bin/bash\nssh -y "$HOSTNAME"  srun "$@"'  > /usr/bin/srun
 chmod +x /usr/bin/srun
